(in-package :keyboard-generator)


(defparameter *dict-key-labels* nil)

(defun generate-identity-labels (a b)
  (loop for i from a to b collect (cons i (write-to-string i))))

(defun generate-empty-labels (a b)
  (loop for i from a to b collect ""))

;; numbering
(setf *dict-key-labels* (generate-identity-labels 1 146))

;; no labels
(setf *dict-key-labels* (generate-empty-labels 1 146))

;; only sharpd and flats
(setf *dict-key-labels*
      '((1 . "")
        (2 . "")
        (3 . "$\\sharp$")
        (4 . "$\\sharp$")
        (5 . "$\\flat$")
        (6 . "$\\flat$")
        (7 . "")
        (8 . "")
        (9 . "$\\sharp$")
        (10 . "$\\sharp$")
        (11 . "$\\flat$")
        (12 . "$\\flat$")
        (13 . "")
        (14 . "")
        (15 . "$\\sharp$")
        (16 . "")
        (17 . "")
        (18 . "$\\sharp$")
        (19 . "$\\sharp$")
        (20 . "$\\flat$")
        (21 . "$\\flat$")
        (22 . "")
        (23 . "")
        (24 . "$\\sharp$")
        (25 . "$\\sharp$")
        (26 . "$\\flat$")
        (27 . "$\\flat$")
        (28 . "")
        (29 . "")
        (30 . "$\\sharp$")
        (31 . "$\\sharp$")
        (32 . "$\\flat$")
        (33 . "$\\flat$")
        (34 . "")
        (35 . "")
        (36 . "$\\sharp$")
        (37 . "")
        (38 . "")
        (39 . "$\\sharp$")
        (40 . "$\\sharp$")
        (41 . "$\\flat$")
        (42 . "$\\flat$")
        (43 . "")
        (44 . "")
        (45 . "$\\sharp$")
        (46 . "$\\sharp$")
        (47 . "$\\flat$")
        (48 . "$\\flat$")
        (49 . "")
        (50 . "")
        (51 . "$\\sharp$")
        (52 . "")
        (53 . "")
        (54 . "$\\sharp$")
        (55 . "$\\sharp$")
        (56 . "$\\flat$")
        (57 . "$\\flat$")
        (58 . "")
        (59 . "")
        (60 . "$\\sharp$")
        (61 . "$\\sharp$")
        (62 . "$\\flat$")
        (63 . "$\\flat$")
        (64 . "")
        (65 . "")
        (66 . "$\\sharp$")
        (67 . "$\\sharp$")
        (68 . "$\\flat$")
        (69 . "$\\flat$")
        (70 . "")
        (71 . "")
        (72 . "$\\sharp$")
        (73 . "")
        (74 . "")
        (75 . "$\\sharp$")
        (76 . "$\\sharp$")
        (77 . "$\\flat$")
        (78 . "$\\flat$")
        (79 . "")
        (80 . "")
        (81 . "$\\sharp$")
        (82 . "$\\sharp$")
        (83 . "$\\flat$")
        (84 . "$\\flat$")
        (85 . "")
        (86 . "")
        (87 . "$\\sharp$")
        (88 . "")
        (89 . "")
        (90 . "$\\sharp$")
        (91 . "$\\sharp$")
        (92 . "$\\flat$")
        (93 . "$\\flat$")
        (94 . "")
        (95 . "")
        (96 . "$\\sharp$")
        (97 . "$\\sharp$")
        (98 . "$\\flat$")
        (99 . "$\\flat$")
        (100 . "")
        (101 . "")
        (102 . "$\\sharp$")
        (103 . "$\\sharp$")
        (104 . "$\\flat$")
        (105 . "$\\flat$")
        (106 . "")
        (107 . "")
        (108 . "$\\sharp$")
        (109 . "")
        (110 . "")
        (111 . "$\\sharp$")
        (112 . "$\\sharp$")
        (113 . "$\\flat$")
        (114 . "$\\flat$")
        (115 . "")
        (116 . "")
        (117 . "$\\sharp$")
        (118 . "$\\sharp$")
        (119 . "$\\flat$")
        (120 . "$\\flat$")
        (121 . "")
        (122 . "")
        (123 . "$\\sharp$")
        (124 . "")
        (125 . "")
        (126 . "$\\sharp$")
        (127 . "$\\sharp$")
        (128 . "$\\flat$")
        (129 . "$\\flat$")
        (130 . "")
        (131 . "")
        (132 . "$\\sharp$")
        (133 . "$\\sharp$")
        (134 . "$\\flat$")
        (135 . "$\\flat$")
        (136 . "")
        (137 . "")
        (138 . "$\\sharp$")
        (139 . "$\\sharp$")
        (140 . "$\\flat$")
        (141 . "$\\flat$")
        (142 . "")
        (143 . "")
        (144 . "$\\sharp$")
        (145 . "")
        (146 . "")))


;; vicentino numbering
(let ((class-list '("C3" "C1" "C4" "D2" "D5" "D3" "D6" "D1" "D4" "E3" "E6" "E2" "E5" "E1" "E4" "F3" "F1" "F4" "G2" "G5" "G3" "G6" "G1" "G4" "A2" "A5" "A3" "A6" "A1" "A4" "B3" "B6" "B2" "B5" "B1" "B4")))
  (setf *dict-key-labels*
        (loop for i from 1 to 146 collect (cons i (nth (mod i 36) class-list)))))
